name: Go / Node

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: node
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          # cache: "npm" # needs lockfile if enabled

      - name: go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.53.1
      - run: npm install
      - run: npm run lint
      - run: npm test
