name: Go / Node

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: node
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          # cache: "npm" # needs lockfile if enabled

      - name: go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.53.1
      - run: npm install
      - run: npm run lint
      - run: npm test
      
  version:
    runs-on: ubuntu-latest
    steps:
      - name: Publish to npm
        working-directory: nodejs/
        run: |
          git config --local user.email "creadbot@brick.com"
          git config --local user.name "creadbot"
          git push --quiet --tags ssh://git@github.com/nmccready/aws-play.git
          npm run standard-version
          npm publish --access public
